name: Build OpenWrt
on:
  workflow_dispatch:
    inputs:
      release:
        description: "release or not"
        required: false
        default: "false"
env:
  OP_REPO: jianshaow/lede
  OP_REPO_BRANCH: master
  BUILD_REPO_PATH: build
  OP_REPO_PATH: lede
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: prepare environment
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
    - name: checkout build script
      uses: actions/checkout@v2.3.4
      with:
        path=${{ env.BUILD_REPO_PATH }}
    - name: checkout op sources
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ env.OP_REPO }}
        path: ${{ env.OP_REPO_PATH }}
